# Generated by Django 5.0.2 on 2024-02-23 18:37

import services.uploader
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='basliq')),
                ('text', models.TextField(verbose_name='metn')),
                ('slider_image', models.ImageField(blank=True, null=True, upload_to=services.uploader.Uploader.upload_photo_index)),
                ('image', models.ImageField(blank=True, null=True, upload_to=services.uploader.Uploader.upload_photo_index1)),
            ],
            options={
                'verbose_name': 'index',
                'verbose_name_plural': 'index',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='mehsulun adi')),
                ('code', models.CharField(max_length=255, verbose_name='mehsulun kodu')),
                ('price', models.FloatField(verbose_name='mehsulun qiymeti')),
                ('discount_price', models.FloatField(verbose_name='mehsulun endirimli qiymeti')),
            ],
            options={
                'verbose_name': 'mehsul',
                'verbose_name_plural': 'mehsullar',
                'ordering': ('-created_at',),
            },
        ),
    ]
