# Generated by Django 5.0.2 on 2024-02-26 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_about_blog_contact_maindetails_sosialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questions', models.CharField(max_length=255, verbose_name='verilen suallar')),
                ('answers', models.CharField(max_length=255, verbose_name='cavblar')),
            ],
            options={
                'verbose_name': 'sorgular',
                'verbose_name_plural': 'sorgular',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='marka adlari')),
            ],
            options={
                'verbose_name': 'marka',
                'verbose_name_plural': 'markalar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveField(
            model_name='about',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='about',
            name='info',
        ),
        migrations.RemoveField(
            model_name='about',
            name='questions',
        ),
        migrations.AddField(
            model_name='product',
            name='is_in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='product info'),
        ),
        migrations.AddField(
            model_name='product',
            name='marka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.marka'),
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='model adlarii')),
                ('marka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.marka')),
            ],
            options={
                'verbose_name': 'model',
                'verbose_name_plural': 'modeller',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.model'),
        ),
    ]
