# Generated by Django 5.0.2 on 2024-02-26 18:38

import services.uploader
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_ask_marka_remove_about_answers_remove_about_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index_About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='basliq')),
                ('text', models.TextField(verbose_name='metn')),
                ('image', models.ImageField(blank=True, null=True, upload_to=services.uploader.Uploader.upload_photo_index1)),
            ],
            options={
                'verbose_name': 'esas sehfe melumat',
                'verbose_name_plural': 'esas sehfe melumatlar',
                'ordering': ('created_at',),
            },
        ),
        migrations.RemoveField(
            model_name='index',
            name='image',
        ),
        migrations.RemoveField(
            model_name='index',
            name='text',
        ),
        migrations.RemoveField(
            model_name='index',
            name='title',
        ),
    ]
